// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [65011720, 604110890],
  relocations: [],
  provenance: [
    { kind: "macro", macro: "j" },
    { kind: "macro", macro: "li" },
  ],
  toolchain: {
    ospCommit: "8e2735bf45e94fbeed617e32cf6dcd7be44d093e",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "2f366a1bec5c75456f5ec8aa46c990e24eeecfb39da0f445aede34d5795a988b",
  wordsSha256:
    "805d2cb84d4ed538e3b1e7ce446f0d1b5e80fb23b88492954fd96844abd2559f",
};
