// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [65011720, 8392737],
  relocations: [],
  provenance: [
    { kind: "macro", macro: "j" },
    { kind: "macro", macro: "move" },
  ],
  toolchain: {
    ospCommit: "8e2735bf45e94fbeed617e32cf6dcd7be44d093e",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "f2e166f941340a80b54002384ee83bf757e6db25e2a433c9446f214471cf1c75",
  wordsSha256:
    "cc2f57dc1c5c5ee329396057543d3064afa7123e129c2762a785689020b6ff60",
};
