// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [65011720, 612499461],
  relocations: [],
  provenance: [
    { kind: "macro", macro: "j" },
    { kind: "macro", macro: "addu" },
  ],
  toolchain: {
    ospCommit: "8e2735bf45e94fbeed617e32cf6dcd7be44d093e",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "87995cd6425d99d39ce6e03b4d38d5d46f7e42dbd290caf09fb406169a5bb883",
  wordsSha256:
    "e393b49e28b6b90487a22a4a92f01931ab986595ae1011a0dbf042d6ad20b4d1",
};
