// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [612499459, 65011720, 135296],
  relocations: [],
  provenance: [
    { kind: "macro", macro: "addu" },
    { kind: "macro", macro: "j" },
    { kind: "instruction" },
  ],
  toolchain: {
    ospCommit: "a0639ea12359ca5e5ba9006bfa65a8a1694f954a",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "995d19ad40c4c720f4a3c2dc038f40ecf147823dbbc0540b80a98f7fb3f21011",
  wordsSha256:
    "60d85d565a34301241797198f654c19a7ce6f5f52cb0ced20ffa860f3bec6d1b",
};
