// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [65011720, 2894397440],
  relocations: [],
  provenance: [{ kind: "macro", macro: "j" }, { kind: "instruction" }],
  toolchain: {
    ospCommit: "a0639ea12359ca5e5ba9006bfa65a8a1694f954a",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "f7ee15bdd2416f8742a545218c9b4a0c94527069adf02990a44a8c378e906729",
  wordsSha256:
    "eb145aa2915f561839a1eff7c9da12adc93c631a1d0f8f08f1581bd859231e5f",
};
