// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [2357329928, 65011720, 0],
  relocations: [],
  provenance: [
    { kind: "instruction" },
    { kind: "macro", macro: "j" },
    {
      kind: "branch-delay-nop",
      note: "the delay slot of jr under .set reorder",
    },
  ],
  toolchain: {
    ospCommit: "a0639ea12359ca5e5ba9006bfa65a8a1694f954a",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "41633bf4cf680f2c336728ad37bbab8180dc6b9ea257671a3afb6914286b01a3",
  wordsSha256:
    "23189ae8e244b06dd430f842010bc837f168609a0ce8a6229cf1e70f5ce53883",
};
