// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [2156003332, 65011720, 0],
  relocations: [],
  provenance: [
    { kind: "instruction" },
    { kind: "macro", macro: "j" },
    {
      kind: "branch-delay-nop",
      note: "the delay slot of jr under .set reorder",
    },
  ],
  toolchain: {
    ospCommit: "a0639ea12359ca5e5ba9006bfa65a8a1694f954a",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "f9946af63f546c025c41dc1f4547b74f1a8e738971712a3ea280e2fd232569ee",
  wordsSha256:
    "3cd9b332ded7e654ea7a074d036e03c51f53b138b228ff1017aaf164d71f4f18",
};
