// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [2357329932, 65011720, 0],
  relocations: [],
  provenance: [
    { kind: "instruction" },
    { kind: "macro", macro: "j" },
    {
      kind: "branch-delay-nop",
      note: "the delay slot of jr under .set reorder",
    },
  ],
  toolchain: {
    ospCommit: "3b5f04f842f8cf5be0b9fbf17041c689bc3a53ce",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "ba7795934dcbdca98f7a2812a8df19454c0fd9b6052faa89a49dc88e1a8a5668",
  wordsSha256:
    "faeaaa0865679b057358c2fbf8adf7c910c2613e87587ef16af5e4b601cd70ac",
};
