// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [2357329924, 0, 2353135620, 65011720, 0],
  relocations: [],
  provenance: [
    { kind: "instruction" },
    { kind: "load-delay-nop", note: "$2 is written by lw and read by lw" },
    { kind: "instruction" },
    { kind: "macro", macro: "j" },
    {
      kind: "branch-delay-nop",
      note: "the delay slot of jr under .set reorder",
    },
  ],
  toolchain: {
    ospCommit: "3b5f04f842f8cf5be0b9fbf17041c689bc3a53ce",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "f7400edebc80217de159c030ee3968acef87b21fbae320ba9a1a744d5e73b385",
  wordsSha256:
    "6df38787201ebb7f26c056c2fdff34e430a608fb04a05e8623a9abb6c92470d9",
};
