// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [2357395488, 0, 2153906180, 65011720, 2892103680],
  relocations: [],
  provenance: [
    { kind: "instruction" },
    { kind: "load-delay-nop", note: "$3 is written by lw and read by lb" },
    { kind: "instruction" },
    { kind: "macro", macro: "j" },
    { kind: "instruction" },
  ],
  toolchain: {
    ospCommit: "a0639ea12359ca5e5ba9006bfa65a8a1694f954a",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "a2209129be1cb1706c7543deb26a5bb8d9766ab31e4aef318c39c93fd5c36350",
  wordsSha256:
    "7911729e2dfd041a525b43afe4904f3707bc779fbd62bdb0ef480c575e051c41",
};
