// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [2223112196, 65011720, 0],
  relocations: [],
  provenance: [
    { kind: "instruction" },
    { kind: "macro", macro: "j" },
    {
      kind: "branch-delay-nop",
      note: "the delay slot of jr under .set reorder",
    },
  ],
  toolchain: {
    ospCommit: "3b5f04f842f8cf5be0b9fbf17041c689bc3a53ce",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "21556c91a11b4af7263df088d7bd3fe8c03b2ff99bf25387856d27515db42ad3",
  wordsSha256:
    "a2b90db6fffe95b16e4be6d396a718547d045e20f7e0b09594f1829091299cba",
};
