// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [2223112204, 65011720, 0],
  relocations: [],
  provenance: [
    { kind: "instruction" },
    { kind: "macro", macro: "j" },
    {
      kind: "branch-delay-nop",
      note: "the delay slot of jr under .set reorder",
    },
  ],
  toolchain: {
    ospCommit: "3b5f04f842f8cf5be0b9fbf17041c689bc3a53ce",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "d58a3ad5934e82dc8b15c666def025b9c34b91d2093c4656aca7871f6615ca63",
  wordsSha256:
    "b84367f5477a26f89f7e934a477dd724a99a9a7311e4d6c4bcd3b457d03ee629",
};
