// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [65011720, 612499468],
  relocations: [],
  provenance: [
    { kind: "macro", macro: "j" },
    { kind: "macro", macro: "addu" },
  ],
  toolchain: {
    ospCommit: "3b5f04f842f8cf5be0b9fbf17041c689bc3a53ce",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "7263a1dab87799006633a82e3d5288231f3b5ca426b021b125207c1d191cff7c",
  wordsSha256:
    "45ae0fe87703ebe3d4c8aa68bc687f0e82ea9ffd6a9603ec2aad2da4dd6b8a0d",
};
