// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [2357329948, 0, 2218917898, 65011720, 0],
  relocations: [],
  provenance: [
    { kind: "instruction" },
    { kind: "load-delay-nop", note: "$2 is written by lw and read by lh" },
    { kind: "instruction" },
    { kind: "macro", macro: "j" },
    {
      kind: "branch-delay-nop",
      note: "the delay slot of jr under .set reorder",
    },
  ],
  toolchain: {
    ospCommit: "ab265a69a9435545f48b84a72d852d92350dd5d2",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "afa0692791bc0afffd3ab95e81f30b290cf7fb2d16eb69c80bc60486c47a9a4e",
  wordsSha256:
    "2333f6432a7edd6ab2f7bb222e947728df56a16e68254924c8178b61d5b3ba27",
};
