// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [65011720, 8720417],
  relocations: [],
  provenance: [{ kind: "macro", macro: "j" }, { kind: "instruction" }],
  toolchain: {
    ospCommit: "b75b6308139cf61404477175fdfa466ce989ba8e",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "3693e03b88c22a8d431aede2d6fdaa36162b76480d8b61f5c52af910973ac125",
  wordsSha256:
    "6e3d0af1356c7afe7c9fae9aeb2100e1db72b42bcfd0040788483f0291dbb967",
};
