// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [65011720, 8720419],
  relocations: [],
  provenance: [{ kind: "macro", macro: "j" }, { kind: "instruction" }],
  toolchain: {
    ospCommit: "b75b6308139cf61404477175fdfa466ce989ba8e",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "0a7784a57cdf2d2904358feead40ae0a84ccb2a1df4efeb72cb6d47c9b4a020f",
  wordsSha256:
    "71bd2a8bb691e128d075ea771511cf38dde73c48dad4a74d298f31af07182745",
};
