// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [8724513, 13045793, 65011720, 8523811],
  relocations: [],
  provenance: [
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "j" },
    { kind: "instruction" },
  ],
  toolchain: {
    ospCommit: "b75b6308139cf61404477175fdfa466ce989ba8e",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "7ca99575832fb240bbcd4d9bc3fa163f222bb72272c57d08d5b582371fc8879b",
  wordsSha256:
    "c61549aff23c4f9b480d68275da0f62be27ef9612cd8fb9a429696a8a6636c37",
};
