// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [65011720, 813826303],
  relocations: [],
  provenance: [{ kind: "macro", macro: "j" }, { kind: "instruction" }],
  toolchain: {
    ospCommit: "b75b6308139cf61404477175fdfa466ce989ba8e",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "bfce91bd3b3a1cbe57639972ba14d1075580102b8ca5c4280539529aaec2bec4",
  wordsSha256:
    "5a814c46b20cc212ccb9d65e293b67127af02253bf910144b1b2732775ea2285",
};
