// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [8724513, 813957375, 12914723, 809631759, 65011720, 8523811],
  relocations: [],
  provenance: [
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "j" },
    { kind: "instruction" },
  ],
  toolchain: {
    ospCommit: "b75b6308139cf61404477175fdfa466ce989ba8e",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "75788c8f9cfaccfb14467f3601e0456f572c28ccbc386e716fd278815ab61350",
  wordsSha256:
    "84f44dde69414441d9d388a2794bf4dda47bc16428a29694cefc7ec5a7c16216",
};
