// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [65011720, 2693070852],
  relocations: [],
  provenance: [{ kind: "macro", macro: "j" }, { kind: "instruction" }],
  toolchain: {
    ospCommit: "b5bb6441b7bb9097eb8461438958c70b94c90683",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "2fc658e40688fd3c5a8f79a465836c9ca08f9f6a62c36b6048b41a3c2cfbd52f",
  wordsSha256:
    "10a1c2a2b130bda2f9ad20972e16ff369b5dab93f648cf9223969fd5b1640284",
};
