// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [65011720, 266498],
  relocations: [],
  provenance: [{ kind: "macro", macro: "j" }, { kind: "instruction" }],
  toolchain: {
    ospCommit: "b5bb6441b7bb9097eb8461438958c70b94c90683",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "d57f4abe8275a235c03b06d4b6351c3c9e90dff4fd18209f9d2c8fa555923849",
  wordsSha256:
    "84b081c0f04cc85769c1efe4f46b917960284410d917b42904bc0a0805e03307",
};
