// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [1006764032, 2353135616, 65011720, 0],
  relocations: [
    {
      offset: 0,
      kind: "HI16",
      fieldMask: 65535,
      fieldValue: 0,
      target: { kind: "symbol", name: "level", addend: 0 },
    },
    {
      offset: 4,
      kind: "LO16",
      fieldMask: 65535,
      fieldValue: 0,
      target: { kind: "symbol", name: "level", addend: 0 },
    },
  ],
  provenance: [
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "j" },
    {
      kind: "branch-delay-nop",
      note: "the delay slot of jr under .set reorder",
    },
  ],
  toolchain: {
    ospCommit: "b5bb6441b7bb9097eb8461438958c70b94c90683",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "9f263c0598e31de9bfd692e81ccf4b3af55ee2acfba75f39a12ff88d75e182c3",
  wordsSha256:
    "9ba82d759a74ed6e068a2b41d68812d6fa2e99772a1b5b58a8cd959bdcd67d9e",
};
