// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [
    2491547648, 2156068866, 135426, 809631759, 4395041, 1006829568, 65011720,
    2690777088,
  ],
  relocations: [
    {
      offset: 20,
      kind: "HI16",
      fieldMask: 65535,
      fieldValue: 0,
      target: { kind: "symbol", name: "last_code", addend: 0 },
    },
    {
      offset: 28,
      kind: "LO16",
      fieldMask: 65535,
      fieldValue: 0,
      target: { kind: "symbol", name: "last_code", addend: 0 },
    },
  ],
  provenance: [
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "j" },
    { kind: "instruction" },
  ],
  toolchain: {
    ospCommit: "b5bb6441b7bb9097eb8461438958c70b94c90683",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "1871c2413f780b9ac93adfb6f7d482ac00aa38ebfd63b338fba2ca4dfd39399a",
  wordsSha256:
    "5d68ca03831344de52e86e4337e5b14f94d894550be5cb2f9abc92b93a6bae27",
};
