// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [65011720, 8720426],
  relocations: [],
  provenance: [{ kind: "macro", macro: "j" }, { kind: "instruction" }],
  toolchain: {
    ospCommit: "48c808d6dda67ae655184f37130f7c906d0c7100",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "53c3ca9134dda205fe734e996d90575bbb8750c10f23e972ea594d546c2cbcff",
  wordsSha256:
    "5af115db365e3d1eb09da66489cdc20af8819b25b53763d9a845dfce398defc1",
};
