// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [65011720, 10752042],
  relocations: [],
  provenance: [{ kind: "macro", macro: "j" }, { kind: "instruction" }],
  toolchain: {
    ospCommit: "48c808d6dda67ae655184f37130f7c906d0c7100",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "c3120e86840d641a53f523a532ea2bd827c1bbffef2bc8ddd600cca841aad193",
  wordsSha256:
    "490efde17fab971e7ee53a17989c475624f0065fa87f1d8131416abb51d8b640",
};
