// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [10752042, 65011720, 943849473],
  relocations: [],
  provenance: [
    { kind: "instruction" },
    { kind: "macro", macro: "j" },
    { kind: "instruction" },
  ],
  toolchain: {
    ospCommit: "48c808d6dda67ae655184f37130f7c906d0c7100",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "0950fdfd44ec8066698b4e229bfd2009e2e7df793ee1b6ecc1ac1bc5d4884a08",
  wordsSha256:
    "cf9b277dbf25ea8a15ffcd08137eb6d1e02a49ffe0703e6ea974b6983fabc652",
};
