// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [65011720, 268226],
  relocations: [],
  provenance: [{ kind: "macro", macro: "j" }, { kind: "instruction" }],
  toolchain: {
    ospCommit: "48c808d6dda67ae655184f37130f7c906d0c7100",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "eaa80639f6df9cafce9bccfac6b52e2e3bc94cdc2402b9d12688636050031322",
  wordsSha256:
    "a74dbb071117f9d477aee2d4153769069d259a8de8ed01da367db5e204d02c1a",
};
