// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [816119823, 266499, 65011720, 10620971],
  relocations: [],
  provenance: [
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "j" },
    { kind: "instruction" },
  ],
  toolchain: {
    ospCommit: "48c808d6dda67ae655184f37130f7c906d0c7100",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "8b33cc00ab5cfcfaf81b3ab03814f03589c405ded0c4b3f1134141b59fc629aa",
  wordsSha256:
    "bbb2e5e5b4c48cdc49f085d80ed962f2eda8e19914d4deadc20c685b513967db",
};
