// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [8724522, 343932930, 604110849, 604110850, 65011720, 0],
  relocations: [],
  provenance: [
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "li" },
    { kind: "macro", macro: "li" },
    { kind: "macro", macro: "j" },
    {
      kind: "branch-delay-nop",
      note: "the delay slot of jr under .set reorder",
    },
  ],
  toolchain: {
    ospCommit: "c240dd1c558872cda5a141967294c6737fd9bdfc",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "b4fe1762bde055946a01e36a763e8edcc7247f91b1422a3cba7b0a5adb293d2b",
  wordsSha256:
    "6cc28376adabbd765fc2762b5bb1c5749c3834237ff461d73a01f655801bfd7a",
};
