// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [343932930, 10489889, 12587041, 65011720, 0],
  relocations: [],
  provenance: [
    { kind: "instruction" },
    { kind: "macro", macro: "move" },
    { kind: "macro", macro: "move" },
    { kind: "macro", macro: "j" },
    {
      kind: "branch-delay-nop",
      note: "the delay slot of jr under .set reorder",
    },
  ],
  toolchain: {
    ospCommit: "c240dd1c558872cda5a141967294c6737fd9bdfc",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "9eaf7125d6cef338e8473673a07d50b74ad21533336f42a10eba27a074998f7b",
  wordsSha256:
    "39a7ca978c0909ffb91a1c9c964e14c16a37b40f7a1bd7e0e96af3d826c5d790",
};
