// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [8724522, 276824066, 604110850, 604110849, 65011720, 0],
  relocations: [],
  provenance: [
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "li" },
    { kind: "macro", macro: "li" },
    { kind: "macro", macro: "j" },
    {
      kind: "branch-delay-nop",
      note: "the delay slot of jr under .set reorder",
    },
  ],
  toolchain: {
    ospCommit: "c240dd1c558872cda5a141967294c6737fd9bdfc",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "38ae20a51c38295ab12c27052582c7ca0ad902dbce0516de568df50e1ef4b507",
  wordsSha256:
    "813c065dc19de2e05f3e48305d00d8238a7b14bf9b7e101c368364dab3c6cb98",
};
