// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [813891839, 6625322, 341835778, 4129, 8392737, 65011720, 0],
  relocations: [],
  provenance: [
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "move" },
    { kind: "macro", macro: "move" },
    { kind: "macro", macro: "j" },
    {
      kind: "branch-delay-nop",
      note: "the delay slot of jr under .set reorder",
    },
  ],
  toolchain: {
    ospCommit: "c240dd1c558872cda5a141967294c6737fd9bdfc",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "6cd65761fe77c00bc064a6f41b4c3041b50b3dbddf877e19fe95e3ffe159bbaf",
  wordsSha256:
    "e979b736d65f52243a490d61557f2e7496cebceae8710ec6b466d4e09ebe8481",
};
