// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [4129, 612696063, 478216190, 608305153, 65011720, 0],
  relocations: [],
  provenance: [
    { kind: "macro", macro: "move" },
    { kind: "macro", macro: "addu" },
    { kind: "instruction" },
    { kind: "macro", macro: "addu" },
    { kind: "macro", macro: "j" },
    {
      kind: "branch-delay-nop",
      note: "the delay slot of jr under .set reorder",
    },
  ],
  toolchain: {
    ospCommit: "1a55b4b9acb5c97d02c01b0c2c8379d524d7cd56",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "0c388661222e917a8406b09eb081ef88c8c016147bd1ca66a130b11b990ba4a0",
  wordsSha256:
    "81671a1c55f424ab08fcf892c0abfb76e80514e6ae783713693d4bad888143a4",
};
