// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [411041796, 4129, 612696063, 478216190, 608305153, 65011720, 0],
  relocations: [],
  provenance: [
    { kind: "instruction" },
    { kind: "macro", macro: "move" },
    { kind: "macro", macro: "addu" },
    { kind: "instruction" },
    { kind: "macro", macro: "addu" },
    { kind: "macro", macro: "j" },
    {
      kind: "branch-delay-nop",
      note: "the delay slot of jr under .set reorder",
    },
  ],
  toolchain: {
    ospCommit: "1a55b4b9acb5c97d02c01b0c2c8379d524d7cd56",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "3ab90fae55c5033687b206efbab501cc34248f393d28c41dc14afd60c17c0791",
  wordsSha256:
    "93602988b943012c43813a12af5bec0cbdf6a52a5e731288f8f93c2a57194ab3",
};
