// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [4129, 4460577, 612696063, 478216190, 4460577, 65011720, 4460579],
  relocations: [],
  provenance: [
    { kind: "macro", macro: "move" },
    { kind: "instruction" },
    { kind: "macro", macro: "addu" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "j" },
    { kind: "instruction" },
  ],
  toolchain: {
    ospCommit: "1a55b4b9acb5c97d02c01b0c2c8379d524d7cd56",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "90faeb44f6c077cb0cab0cb108c51416f8429d86671e6db5814b3553a08befe3",
  wordsSha256:
    "b41c29452935e0904e27c77c5fd07a1c99bd302d0e49113d48a7b916acba43fb",
};
