// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [
    6177, 413138951, 6303777, 2357329920, 610467841, 12726305, 6623274,
    339804155, 612630532, 65011720, 12587041,
  ],
  relocations: [],
  provenance: [
    { kind: "macro", macro: "move" },
    { kind: "instruction" },
    { kind: "macro", macro: "move" },
    { kind: "instruction" },
    { kind: "macro", macro: "addu" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "addu" },
    { kind: "macro", macro: "j" },
    { kind: "macro", macro: "move" },
  ],
  toolchain: {
    ospCommit: "1a55b4b9acb5c97d02c01b0c2c8379d524d7cd56",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "0078a2b411d685acc56116f600c390a6eda0d57de35c5bf6073dd1ff35311dda",
  wordsSha256:
    "75f516100694286feaa007a923534ab81de0290289ba0d10fe6a21d83208b994",
};
