// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [
    813957121, 276824067, 0, 134217728, 614596609, 614662143, 65011720, 135235,
  ],
  relocations: [
    {
      offset: 12,
      kind: "MIPS26",
      fieldMask: 67108863,
      fieldValue: 0,
      target: { kind: "section", section: ".text", offset: 24, label: "$L3" },
    },
  ],
  provenance: [
    { kind: "instruction" },
    { kind: "instruction" },
    {
      kind: "branch-delay-nop",
      note: "the delay slot of beq under .set reorder",
    },
    { kind: "instruction" },
    { kind: "macro", macro: "addu" },
    { kind: "macro", macro: "addu" },
    { kind: "macro", macro: "j" },
    { kind: "instruction" },
  ],
  toolchain: {
    ospCommit: "1a55b4b9acb5c97d02c01b0c2c8379d524d7cd56",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "4e7bd2818fc480b4c64b0a73b8813d9f3e5e605a18a4016fc0e356f5ef74ea32",
  wordsSha256:
    "5fec188a337b36a42194d50d19e220cc7c017a33a1c470be9c1da588fa5ece0d",
};
