// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [
    413138955, 4129, 2357395456, 0, 73465859, 0, 134217728, 4395043, 4395041,
    614858751, 480313335, 612630532, 65011720, 0,
  ],
  relocations: [
    {
      offset: 24,
      kind: "MIPS26",
      fieldMask: 67108863,
      fieldValue: 0,
      target: { kind: "section", section: ".text", offset: 36, label: "$L6" },
    },
  ],
  provenance: [
    { kind: "instruction" },
    { kind: "macro", macro: "move" },
    { kind: "instruction" },
    { kind: "load-delay-nop", note: "$3 is written by lw and read by bgez" },
    { kind: "instruction" },
    {
      kind: "branch-delay-nop",
      note: "the delay slot of bgez under .set reorder",
    },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "addu" },
    { kind: "instruction" },
    { kind: "macro", macro: "addu" },
    { kind: "macro", macro: "j" },
    {
      kind: "branch-delay-nop",
      note: "the delay slot of jr under .set reorder",
    },
  ],
  toolchain: {
    ospCommit: "1a55b4b9acb5c97d02c01b0c2c8379d524d7cd56",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "f3f9953f8f29290ab4d2d17b8c7315950392018c7ba78ff3582c3902adaef003",
  wordsSha256:
    "940948dd674f138e30990f426812b115d508caa67fe759e15a96c5b9ca654871",
};
