// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [
    666763240, 2948530192, 201326592, 0, 2411659280, 608305153, 65011720,
    666697752,
  ],
  relocations: [
    {
      offset: 8,
      kind: "MIPS26",
      fieldMask: 67108863,
      fieldValue: 0,
      target: { kind: "symbol", name: "helper", addend: 0 },
    },
  ],
  provenance: [
    { kind: "macro", macro: "subu" },
    { kind: "instruction" },
    { kind: "instruction" },
    {
      kind: "branch-delay-nop",
      note: "the delay slot of jal under .set reorder",
    },
    { kind: "instruction" },
    { kind: "macro", macro: "addu" },
    { kind: "macro", macro: "j" },
    { kind: "macro", macro: "addu" },
  ],
  toolchain: {
    ospCommit: "2e801fe6e6aee425059be372b4e6d6d8c52a22eb",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "b62bf75dbc81277400ddf2eb4bc057f77aa34e86308ad2da3e30a0645e238830",
  wordsSha256:
    "edcdfd6bce981affbc8370aaf52c8d5ef589159de7f858cfdf4b9df22b8013cb",
};
