// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [
    666763232, 2946760720, 2948530200, 201326592, 665059344, 2411659288, 0,
    65011720, 666697760,
  ],
  relocations: [
    {
      offset: 12,
      kind: "MIPS26",
      fieldMask: 67108863,
      fieldValue: 0,
      target: { kind: "symbol", name: "fill", addend: 0 },
    },
  ],
  provenance: [
    { kind: "macro", macro: "subu" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "addu" },
    { kind: "instruction" },
    { kind: "load-delay-nop", note: "$31 is written by lw and read by jr" },
    { kind: "macro", macro: "j" },
    { kind: "macro", macro: "addu" },
  ],
  toolchain: {
    ospCommit: "2e801fe6e6aee425059be372b4e6d6d8c52a22eb",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "653e6b81568bd1c5a360de15d856644b061b51384c9a39662d96be6189964ea7",
  wordsSha256:
    "612b0099be178c948abf655264d8ae60ec8d3b34447abf5a1e00b69bd8bc54c2",
};
