// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [
    666763232, 8400929, 10500129, 2948530200, 201326592, 2946760720, 2411659288,
    0, 65011720, 666697760,
  ],
  relocations: [
    {
      offset: 16,
      kind: "MIPS26",
      fieldMask: 67108863,
      fieldValue: 0,
      target: { kind: "symbol", name: "mix", addend: 0 },
    },
  ],
  provenance: [
    { kind: "macro", macro: "subu" },
    { kind: "macro", macro: "move" },
    { kind: "macro", macro: "move" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "load-delay-nop", note: "$31 is written by lw and read by jr" },
    { kind: "macro", macro: "j" },
    { kind: "macro", macro: "addu" },
  ],
  toolchain: {
    ospCommit: "2e801fe6e6aee425059be372b4e6d6d8c52a22eb",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "c5d2a50567a83fed1cda04738c989d0d268154bebd70a9a94c9712d515b0fa77",
  wordsSha256:
    "4e7eb7fe1e7b40a663aa589bd3d250c6aa8ca07e8ae6d7eeacd240a2c440120e",
};
