// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [
    666763240, 2947547152, 2948530196, 201326592, 8421409, 5247009, 2411659284,
    2410676240, 65011720, 666697752,
  ],
  relocations: [
    {
      offset: 12,
      kind: "MIPS26",
      fieldMask: 67108863,
      fieldValue: 0,
      target: { kind: "symbol", name: "helper", addend: 0 },
    },
  ],
  provenance: [
    { kind: "macro", macro: "subu" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "move" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "j" },
    { kind: "macro", macro: "addu" },
  ],
  toolchain: {
    ospCommit: "2e801fe6e6aee425059be372b4e6d6d8c52a22eb",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "b0092f18078fc797d945615ef498be37b0e4f839be86669b454fa0ea24e95c9e",
  wordsSha256:
    "b216b16586fc8d85194de1f6bcdb56e47dab8480a33ab967166753f12bc2f182",
};
