// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [
    666763232, 2947547152, 10518561, 2947612692, 2948530200, 201326592,
    12617761, 5247009, 5312545, 2411659288, 2410741780, 2410676240, 65011720,
    666697760,
  ],
  relocations: [
    {
      offset: 20,
      kind: "MIPS26",
      fieldMask: 67108863,
      fieldValue: 0,
      target: { kind: "symbol", name: "helper", addend: 0 },
    },
  ],
  provenance: [
    { kind: "macro", macro: "subu" },
    { kind: "instruction" },
    { kind: "macro", macro: "move" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "move" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "j" },
    { kind: "macro", macro: "addu" },
  ],
  toolchain: {
    ospCommit: "2e801fe6e6aee425059be372b4e6d6d8c52a22eb",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "132ff848277194a30609b4ca1fb47bbe7e6f39beee7a124ca2a25834eabd44b7",
  wordsSha256:
    "e9075bb4ab14c6b42888ce95f61c7f91c93ac4c6d8f38bc2aaf6e0efe4eb1a76",
};
