// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [
    8732705, 10889249, 13053985, 14956577, 17109030, 13047846, 4395041,
    17186852, 4722721, 10954789, 65011720, 4526113,
  ],
  relocations: [],
  provenance: [
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "j" },
    { kind: "instruction" },
  ],
  toolchain: {
    ospCommit: "2e801fe6e6aee425059be372b4e6d6d8c52a22eb",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "20dd0c16ddf964095fd09a5a82c824d0810859c8f218415d2af89e090f72e6e1",
  wordsSha256:
    "9b32eda5cf733181b851b9be00b16e54afb0e1f44365687604d66aef4fee402d",
};
