// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [
    666763232, 2947547152, 8421409, 2947612692, 34849, 436207622, 2948530200,
    201326592, 33562657, 638648319, 503382012, 35817505, 35655713, 2411659288,
    2410741780, 2410676240, 65011720, 666697760,
  ],
  relocations: [
    {
      offset: 28,
      kind: "MIPS26",
      fieldMask: 67108863,
      fieldValue: 0,
      target: { kind: "symbol", name: "helper", addend: 0 },
    },
  ],
  provenance: [
    { kind: "macro", macro: "subu" },
    { kind: "instruction" },
    { kind: "macro", macro: "move" },
    { kind: "instruction" },
    { kind: "macro", macro: "move" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "move" },
    { kind: "macro", macro: "addu" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "move" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "j" },
    { kind: "macro", macro: "addu" },
  ],
  toolchain: {
    ospCommit: "2e801fe6e6aee425059be372b4e6d6d8c52a22eb",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "beadd5a616da1a0eb5949abf7e12d4b54baa5caed226a4683cc4e9fe06cd1eed",
  wordsSha256:
    "623bf1a7d8ef9e45de0208aa80d09bddf1278e4b9a4a62c54193f737fedbeff6",
};
