// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [
    6177, 413138952, 6303777, 2357329920, 610467841, 137154, 12726305, 6623274,
    339804154, 612630532, 65011720, 12587041,
  ],
  relocations: [],
  provenance: [
    { kind: "macro", macro: "move" },
    { kind: "instruction" },
    { kind: "macro", macro: "move" },
    { kind: "instruction" },
    { kind: "macro", macro: "addu" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "addu" },
    { kind: "macro", macro: "j" },
    { kind: "macro", macro: "move" },
  ],
  toolchain: {
    ospCommit: "dde146d1659912457d113e64b27834f2c89cb7c4",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "4edb11310b164549f710f2bf9d709c8837b48dd72a701859bf9805540f1e06c7",
  wordsSha256:
    "da144cd8a6532ad17e41ca8495e7e07022aa6b30e39effae9ab101b3d9e41627",
};
