// Generated by `pnpm curriculum:targets` from the mission's OSP-authored
// solution with the pinned compiler and assembler. Do not edit.
import type { InlineTarget } from "@osp/mission-schema";

export const target: InlineTarget = {
  kind: "inline",
  words: [
    2410151952, 18465, 19417121, 621346815, 486604798, 19417121, 19417123,
    8720422, 19009569, 13047846, 65011720, 4395041,
  ],
  relocations: [],
  provenance: [
    { kind: "instruction" },
    { kind: "macro", macro: "move" },
    { kind: "instruction" },
    { kind: "macro", macro: "addu" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "instruction" },
    { kind: "macro", macro: "j" },
    { kind: "instruction" },
  ],
  toolchain: {
    ospCommit: "dde146d1659912457d113e64b27834f2c89cb7c4",
    psyqWasmVersion: "1.0.0",
    compilerBuildId: "sha256:e3cdde0d4dc69a95",
    preprocessorBuildId: "sha256:12af84fbb68197fb",
    psyqAsmVersion: "0.2.0",
  },
  solutionSha256:
    "8470dbd102453071a5bc177a0daa8486fa86206385fe3771e49aa580465b0170",
  wordsSha256:
    "2647cb08ab430504dd7625191e59bf4f9be53004739d88e00617da93a2ba8164",
};
